---
title: "Biomart Gene Ontology Gene Sets Collections"
author: "Zuguang Gu ( z.gu@dkfz.de )"
date: '`r Sys.Date()`'
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_collapsed: false
    toc_float: true
---

```{r, echo = FALSE, message = FALSE}
library(knitr)
knitr::opts_chunk$set(
    error = FALSE,
    tidy  = FALSE,
    message = FALSE,
    echo = FALSE)
library(GetoptLong)
library(rGREAT)
```



```{r}
df_genes = read.csv("00_genes_mart.csv")
df_plants = read.csv("00_plants_mart.csv")
df_metazoa = read.csv("00_metazoa_mart.csv")
df_fungi = read.csv("00_fungi_mart.csv")
df_protists = read.csv("00_protists_mart.csv")

add_columns = function(df) {
	colnames(df) = c("Dataset", "Description", "Version")
	df$Genes = qq("[genes](genes/granges_@{df[, 1]}_genes.rds)", collapse = FALSE)
	df[["Gene sets"]] = qq("[BP](genesets/bp_@{df[, 1]}_go_genesets.rds), [CC](genesets/cc_@{df[, 1]}_go_genesets.rds), [MF](genesets/mf_@{df[, 1]}_go_genesets.rds)", collapse = FALSE)
	df
}

df_genes = add_columns(df_genes)
df_plants = add_columns(df_plants)
df_metazoa = add_columns(df_metazoa)
df_fungi = add_columns(df_fungi)
df_protists = add_columns(df_protists)
```


The data were retrieved from BioMart on 2022-05-24. The R script can be found at https://github.com/jokergoo/rGREAT/blob/master/inst/extdata/biomart_genesets.R.

## Ensembl organisms (`r nrow(df_genes)` organisms)

```{r}
kable(df_genes)
```

## Ensembl plants (`r nrow(df_plants)` organisms)

```{r}
kable(df_plants)
```

## Ensembl metazoa (`r nrow(df_metazoa)` organisms)

```{r}
kable(df_metazoa)
```

## Ensembl fungi (`r nrow(df_fungi)` organisms)

```{r}
kable(df_fungi)
```

## Ensembl protists (`r nrow(df_protists)` organisms)

```{r}
kable(df_protists)
```

